# 工作目录，存储输出日志，Agent持久化的相关内容 默认当前目录
#WorkDir: /home/user
# 日志输出级别
LogLevel: info
# 审计日志路径
#AuditLogPath: /home/user/audit.log
# 系统日志路径
#SysLogPath: /home/user/sys.log
# 连接agent超时时间(毫秒)
AgentTimeout: 600000
# 服务端口号
Port: 7021
# 数据库连接地址

DBArgs: "adc_rw:aJXh&UArz!w6C5fG@tcp(10.153.40.162:3306)/adc?charset=utf8&parseTime=True"
# 数据库驱动名称
Dialect: mysql
# 需要连接的etcd地址
EtcdEndpoints:
  - https://10.153.51.208:2379
  - https://10.153.51.209:2379
  - https://10.153.51.210:2379
# Etcd 证书双向认证
EtcdTLS:
   ca: config/release/tls/ca.crt
   cert: config/release/tls/peer.crt
   key: config/release/tls/peer.key
